theme                     : jekyll-theme-leap-day

# Site Settings
locale                    : "fa-IR"
title                     : "پردازش سیگنال دیجیتال در متلب"
name                      : "سعید محققی Saeed Mohagheghi"

description               : "پردازش سیگنال دیجیتال در متلب"
show_downloads            : true
